spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    url: 'jdbc:postgresql://localhost:5432/doc_recognizer'
    username: 'admin'
    password: 'password'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
security:
  config:
    password-flow: true
    authcode-flow: false
keycloak:
  auth-server-url: https://keycloak.yamakassi.ru/auth
  realm: "test"
  resource: "test"
  bearer-only: true


services:
  uni-file-archive:
    url: "http://5.42.80.41:8080/uni-files/download/"
  yandexapi:
    token: ${YANDEX_TOKEN_API}
    folderId: ${YANDEX_FOLDER_ID}
  tests-env:
    username: ${USERNAME}
    password: ${PASSWORD}
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
springdoc:
  swagger-ui:
    oauth:
      client-id: "your-client-id-value"
      client-secret: "your-client-secret-value"
server:
  port: 8081
logging:
  level:
    com.rowi.docrecognizerapi: DEBUG
