spring:
  cloud:
    vault:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/doc-recognizer-api
    username: admin
    password: password

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: none
    show-sql: true

  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true

keycloak:
  auth-server-url: https://keycloak.yamakassi.ru
  realm: test
  resource: test
  bearer-only: true


services:
  uni-file-archive:
    url: "http://5.42.80.41:8888/uni-files/download/"
  yandexapi:
    token: ${YANDEX_TOKEN_API}
    folderId: ${YANDEX_FOLDER_ID}
  tests-env:
    username: ${USERNAME}
    password: ${PASSWORD}
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
server:
  port: 8081
logging:
  level:
    tech.rowi.rko.docrecognizerapi: DEBUG
